#!/usr/bin/env python3
"""Persist the T3 literature-survey annotated bibliography as CSV."""
import csv, os

OUT = "/Users/pete/space_training/web_data/results/t3_literature_survey.csv"

ROWS = [
 dict(key="LaFarge2020", title="Guidance for Closed-Loop Transfers using Reinforcement Learning with Application to Libration Point Orbits",
      authors="LaFarge, Miller, Howell, Linares", venue="AIAA SciTech 2020",
      url="https://engineering.purdue.edu/people/kathleen.howell.1/Publications/Conferences/2020_AIAA_LafMilHowLin.pdf",
      category="RL transfer / reference-tracking shaping", solves_phasing="no (tracks a precomputed reference)",
      transfer="Reward = eta*exp(-lambda*k) on distance k to NEAREST STATE of a precomputed reference trajectory (KD-tree lookup), + arrival bonus b=25, divergence penalty -4, impact -10, episode terminated on divergence. eta=i/(n*xi)+1 ramps reward along the reference to kill the stationkeeping local optimum. gamma=0.9, ~150 steps/episode, 100k episodes, 60 identical agents trained and best selected."),
 dict(key="Holt2024", title="Reinforced Lyapunov controllers for low-thrust lunar transfers",
      authors="Holt, Baresi, Armellin", venue="Astrodynamics 8(4):633-656, 2024",
      url="https://doi.org/10.1007/s42064-024-0212-x",
      category="RL-modulated classical law + explicit phasing", solves_phasing="yes, but classically (a-augmentation), not by RL",
      transfer="RL learns state-dependent WEIGHTS of a Lyapunov/Q-law rather than the control itself -> 100% MC convergence and 9-12% cost improvement over the hand-tuned law. Section 6 handles phase by AUGMENTING THE TARGET SEMI-MAJOR AXIS: a*_T = [(1/a_T)^{3/2} + W_L*sgn(dL)*arccos(cos dL)/exp(N_tt)]^{-2/3} with N_tt = revs-to-go from the Q-law time-to-go. This is the single most transferable equation in the survey."),
 dict(key="Naasz2002", title="Classical Element Feedback Control for Spacecraft Orbital Maneuvers (mean-motion control / target-a augmentation)",
      authors="Naasz", venue="MS thesis, Virginia Tech, 2002",
      url="https://vtechworks.lib.vt.edu/items/6a04a7a1-9bd2-4b53-8b0f-2b3aa1e01e5b",
      category="classical GNC", solves_phasing="yes",
      transfer="Origin of the 'use a as a proxy for period, bias the target a by the phase error' trick that later Q-law/RLC work builds on. Establishes asymptotic convergence of orbital-element feedback augmented by mean-motion control."),
 dict(key="ConstrainedLyapunov2026", title="Constrained Lyapunov Stabilization based on Gauss Variational Equations: From Spacecraft Orbital Transfers to Rendezvous",
      authors="(arXiv 2606.12108)", venue="arXiv 2026",
      url="https://arxiv.org/abs/2606.12108",
      category="classical GNC, modern statement", solves_phasing="yes",
      transfer="Explicit outer-loop: n_mod = sat(n_des - lambda*z^T S^T Pbar (z - z_des)) on the mean-anomaly phase state z on the unit circle, then a_des_mod = clip((mu/n_mod^2)^(1/3), 0.8 a_des, 1.2 a_des). +-20% saturation on the commanded a is the drift-orbit sizing limit. Handles +3 / -2 revolution phase gaps. Directly usable as our expert controller and as the shaping target."),
 dict(key="Vallado/Curtis-phasing", title="Phasing maneuvers (co-orbital two-impulse phasing)",
      authors="Vallado 'Fundamentals of Astrodynamics and Applications' ch.6; Curtis ch.6",
      venue="textbook", url="https://orbital-mechanics.space/orbital-maneuvers/phasing-maneuvers.html",
      category="classical", solves_phasing="yes (canonical)",
      transfer="T_ph = T*(1 - dtheta/(2 pi N)); a_ph = (mu (T_ph/2pi)^2)^{1/3}; dv_total = 2|sqrt(mu(2/a-1/a_ph)) - sqrt(mu/a)|. Worked GEO example shows dv falls ~7x from N=0 to N=1 rev. Same monotone structure holds in our LEO band (see t3_phasing_design_table.csv)."),
 dict(key="Shirobokov2021", title="Propulsionless planar phasing of multiple satellites using deep reinforcement learning",
      authors="Sumanth Kumar / Shirobokov et al.", venue="Advances in Space Research 67(11):3667, 2021",
      url="https://doi.org/10.1016/j.asr.2020.09.025",
      category="deep RL that actually targets PHASING", solves_phasing="yes (differential drag, propellantless)",
      transfer="Closest published analogue to our hard leg: A2C and PPO agents rephase relative argument of latitude of 3 coplanar LEO satellites by commanding cross-sectional area (differential drag). Uses a surrogate propagator to make multi-week horizons trainable. Confirms (a) phasing IS learnable by PPO when the horizon is compressed by a surrogate/abstraction, (b) the action is a slow drift-rate knob, not an impulse."),
 dict(key="Zhao2023-multi-impulse", title="Optimal Multi-impulse Linear Rendezvous via Reinforcement Learning",
      authors="(Space: Science & Technology)", venue="Space Sci. Technol. 2023, art. 0047",
      url="https://spj.science.org/doi/10.34133/space.0047",
      category="RL with coast-duration in the action", solves_phasing="partially (linear/CW, multi-impulse)",
      transfer="Action = (impulse dv, coasting period dt) jointly. Explicit precedent for our time-warp actions being part of the action vector rather than a fixed frame-skip. Reward reflects fuel, transfer time, relative state."),
 dict(key="Federici2021", title="Reinforcement Learning for Robust Trajectory Design of Interplanetary Missions",
      authors="Zavoli, Federici", venue="JGCD 44(8), 2021 / arXiv:2008.08501",
      url="https://arxiv.org/abs/2008.08501",
      category="RL long-horizon low-thrust", solves_phasing="no (fixed-time, MEE state)",
      transfer="PPO on a time-discrete MDP with equinoctial state; the value of a stochastic-disturbance training distribution as robustness. Their later 'Densely rewarded RL' (ASR 72(4), 2023) is the explicit statement that sparse terminal rewards generalize better but cost far more training, dense rewards train fast but bias the optimum."),
 dict(key="Federici2023-dense", title="Densely rewarded reinforcement learning for robust low-thrust trajectory optimization",
      authors="Federici, Zavoli", venue="Advances in Space Research 72(4), 2023",
      url="https://doi.org/10.1016/j.asr.2023.04.007",
      category="reward design", solves_phasing="no",
      transfer="The sparse-vs-dense tradeoff stated cleanly for astrodynamics: dense shaping buys sample efficiency at the price of biasing toward the shaping designer's assumed solution. This is exactly what happened to us: the shaping encoded 'stay on the target orbit', which was only optimal because the bug let phase be teleported."),
 dict(key="Gaudet2020", title="Six Degree-of-Freedom Hovering / Terminal adaptive guidance via reinforcement meta-learning",
      authors="Gaudet, Linares, Furfaro", venue="AIAA SciTech 2020; Acta Astronautica",
      url="https://arxiv.org/abs/1911.08553",
      category="RL prox-ops (terminal only)", solves_phasing="no",
      transfer="The canonical RL-for-spacecraft line, but every task is TERMINAL: seconds-to-minutes, last few km, sensor-to-thrust. Recurrent policy (meta-RL) adapts to unknown dynamics. Their shaping is a velocity-field / glideslope tracking term, i.e. also 'shape toward a guidance law', which is the reusable idea."),
 dict(key="Hovell2021", title="Deep Reinforcement Learning for Spacecraft Proximity Operations Guidance",
      authors="Hovell, Ulrich", venue="J. Spacecraft & Rockets 58(2), 2021",
      url="https://carleton.ca/spacecraft/wp-content/uploads/sites/229/JSR-2021.pdf",
      category="RL prox-ops (terminal only)", solves_phasing="no",
      transfer="Deep GUIDANCE, not deep control: the policy outputs velocity commands that a conventional controller tracks. Lowers the learning burden and gives sim-to-real transfer (granite-table hardware). Analogue for us: let the policy output a commanded delta-a / drift rate and let a classical law realize it."),
 dict(key="FarRange2025", title="Robust trajectory design and guidance for far-range rendezvous using reinforcement learning with safety and observability considerations",
      authors="(Aerospace Science & Technology)", venue="Aerosp. Sci. Technol. 2025",
      url="https://doi.org/10.1016/j.ast.2025.109930",
      category="far-range RPO", solves_phasing="no - phasing done by a separate nonlinear optimizer/PSO",
      transfer="Architecture split worth copying: a global optimizer (PSO / NLP) designs the nominal far-range trajectory, PPO only provides the closed-loop correction around it. Reports 22.3% dv reduction vs best benchmark. Companion arXiv:2411.01021 is the ADR version."),
 dict(key="Guffanti2023-ART", title="Transformers for Trajectory Optimization with Application to Spacecraft Rendezvous (ART)",
      authors="Guffanti, Gammelli, D'Amico, Pavone", venue="IEEE Aerospace 2024 / arXiv:2310.13831",
      url="https://arxiv.org/abs/2310.13831",
      category="sequence model warm-start", solves_phasing="no (OCP horizon 1-3 orbits, 416 km)",
      transfer="Uses ROE state; transformer trained on 400k optimal trajectories to WARM-START a sequential convex optimizer, keeping hard-constraint guarantees. Alternative to RL if we ever need the last mile. Confirms the field's horizon norm is 1-3 orbits."),
 dict(key="RL-ROE-SK2025", title="Reinforcement learning-based station keeping using relative orbital elements",
      authors="(Advances in Space Research 2025)", venue="Adv. Space Res. 2025",
      url="https://doi.org/10.1016/j.asr.2025.05.031",
      category="state representation", solves_phasing="partially (relative mean longitude control)",
      transfer="ROE observation: d_a drives secular drift of relative mean longitude d_lambda; the pair (d_a, d_lambda) is the natural 2-D phase-plane for our problem. Strong argument to feed the policy (d_a, d_lambda, d_e_vector) rather than raw a/e/theta."),
 dict(key="MultiDebris2024", title="Revisiting Space Mission Planning: A RL-Guided Approach for Multi-Debris Rendezvous",
      authors="(arXiv 2409.16882) and follow-ons", venue="arXiv 2024/2026",
      url="https://arxiv.org/abs/2409.16882",
      category="RL for the discrete layer only", solves_phasing="no - Lambert solver does each leg",
      transfer="Masked PPO picks the debris VISIT SEQUENCE; a Lambert solver executes each transfer. ~11-14% mission-time improvement. The division of labour (RL = discrete/combinatorial, classical = continuous leg) is a legitimate fallback framing for our project."),
 dict(key="OrbitZoo2025", title="OrbitZoo: Real Orbital Systems Challenges for Reinforcement Learning",
      authors="(arXiv 2504.04160)", venue="arXiv 2025",
      url="https://arxiv.org/abs/2504.04160",
      category="benchmark", solves_phasing="no (Hohmann ~30 km, GEO constellation spacing, chase-target)",
      transfer="Benchmark tasks are deliberately small (30 km altitude change). Explicitly names sparse/delayed feedback, credit assignment, reward misspecification and curriculum as the OPEN problems in orbital RL. Recommends equinoctial elements to avoid circular/equatorial singularities."),
 dict(key="Biedenkapp2021", title="TempoRL: Learning When to Act",
      authors="Biedenkapp, Rajan, Hutter, Lindauer", venue="ICML 2021",
      url="https://arxiv.org/abs/2106.05262",
      category="semi-MDP / temporal abstraction", solves_phasing="n/a",
      transfer="Factor the policy into (what action, how long to hold it) with the skip-length head CONDITIONED ON THE CHOSEN ACTION. Reported far more stable than FiGAR/DAR as max skip length grows. Our 3 warp actions are a hand-coded, action-independent version of this; a (burn, hold-duration) factorization is the principled upgrade."),
 dict(key="Sharma2017-FiGAR", title="Learning to Repeat: Fine Grained Action Repetition for Deep Reinforcement Learning (FiGAR)",
      authors="Sharma, Lakshminarayanan, Ravindran", venue="ICLR 2017",
      url="https://arxiv.org/abs/1702.06054",
      category="semi-MDP / temporal abstraction", solves_phasing="n/a",
      transfer="Second policy head emits a repetition count from a discrete set; shows large gains on long-horizon tasks. Cheapest possible upgrade to our action space: keep 16 actions, add a 4-way duration head."),
 dict(key="Sutton1999-options", title="Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning",
      authors="Sutton, Precup, Singh", venue="Artificial Intelligence 112, 1999",
      url="https://doi.org/10.1016/S0004-3702(99)00052-1",
      category="theory", solves_phasing="n/a",
      transfer="The SMDP Bellman equation with gamma^tau discounting over option duration tau. Our shaping term beta*(gamma^tau*Phi(s') - Phi(s)) is the correct SMDP-consistent form; confirms that part of the env is right."),
 dict(key="Ng1999", title="Policy invariance under reward transformations: theory and application to reward shaping",
      authors="Ng, Harada, Russell", venue="ICML 1999",
      url="https://people.eecs.berkeley.edu/~russell/papers/ml99-shaping.pdf",
      category="theory", solves_phasing="n/a",
      transfer="Potential-based shaping preserves the optimal policy ONLY in the limit; with finite training it changes which optimum is found first. Our Phi is potential-based and therefore does not change the true optimum - it changes what the agent can find, which is exactly the failure we observe."),
 dict(key="Florensa2017", title="Reverse Curriculum Generation for Reinforcement Learning",
      authors="Florensa, Held, Wulfmeier, Zhang, Abbeel", venue="CoRL 2017",
      url="https://arxiv.org/abs/1707.05300",
      category="curriculum", solves_phasing="n/a",
      transfer="Automatically expand the START-STATE distribution outward from the goal, gated on measured success rate (keep starts with success in [0.1,0.9]). Our fixed 30->90->180 deg schedule is a coarse hand-made version; the adaptive version is strictly better and cheap to implement (sample init_phase_gap from a moving frontier)."),
 dict(key="Andrychowicz2017-HER", title="Hindsight Experience Replay",
      authors="Andrychowicz et al.", venue="NeurIPS 2017",
      url="https://arxiv.org/abs/1707.01495",
      category="sparse-reward", solves_phasing="n/a",
      transfer="Relabel failed episodes with the achieved goal. Applicable here because our goal (target orbit + phase) is an explicit part of the observation: an episode that ends 40 deg short is a perfect demonstration for a 40-deg-smaller phase gap. Requires an off-policy learner (SAC/TD3/DDPG), which PufferLib PPO is not - this is the main cost."),
 dict(key="PursuitEvasion2024-HER", title="Impulsive maneuver strategy for multi-agent orbital pursuit-evasion game under sparse rewards",
      authors="(Aerospace Science & Technology 2024)", venue="Aerosp. Sci. Technol. 2024",
      url="https://doi.org/10.1016/j.ast.2024.109722",
      category="sparse-reward orbital RL", solves_phasing="no",
      transfer="DDPG+HER with a hierarchical network for impulsive orbital maneuvers under sparse reward - existence proof that HER works on impulsive orbital problems, not just robot arms."),
 dict(key="Abbas2023-plasticity", title="Loss of Plasticity in Continual Deep Reinforcement Learning",
      authors="Abbas, Zhao, Modayil, White, Machado", venue="CoLLAs 2023 / arXiv:2303.07507",
      url="https://arxiv.org/abs/2303.07507",
      category="warm-start / continual RL", solves_phasing="n/a",
      transfer="Directly explains our R3/R5 result that warm-started continuation collapses: the network loses the ability to learn after committing to one task. Mitigations that are cheap for us: shrink-and-perturb on the trunk, ReDo-style dormant-unit resets, or full re-init of the head."),
 dict(key="Dohare2024", title="Loss of plasticity in deep continual learning",
      authors="Dohare, Hernandez-Garcia, Lan, Rahman, Mahmood, Sutton", venue="Nature 632, 2024",
      url="https://www.nature.com/articles/s41586-024-07711-7",
      category="warm-start / continual RL", solves_phasing="n/a",
      transfer="Continual backpropagation (reinitialize a small fraction of least-used units each step) is the only intervention that maintained plasticity indefinitely. ~20 lines in a PufferLib training loop; the highest-value cheap experiment if we keep any warm-start in the curriculum."),
 dict(key="Tipaldi2022", title="Reinforcement learning in spacecraft control applications: Advances, prospects, and challenges",
      authors="Tipaldi, Iervolino, Massenio", venue="Annual Reviews in Control 54, 2022",
      url="https://doi.org/10.1016/j.arcontrol.2022.07.004",
      category="survey", solves_phasing="no",
      transfer="Use as the citation for 'the field is terminal-phase dominated'. Good source for framing our contribution as filling the far-range/phasing gap."),
 dict(key="Hovell2022-HRL-cubesat", title="Hierarchical Deep Reinforcement Learning for cubesat guidance and control",
      authors="(Control Engineering Practice 2024)", venue="Control Eng. Practice 2024",
      url="https://doi.org/10.1016/j.conengprac.2024.106133",
      category="HRL", solves_phasing="no (short-range rendezvous)",
      transfer="Hierarchical actor-critic (HAC) + DDPG with policies at DIFFERENT TIME RESOLUTIONS for simultaneous guidance and attitude control, validated hardware-in-the-loop. Closest published HRL-for-rendezvous precedent; note it is still short-range."),
]

def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(ROWS[0].keys()))
        w.writeheader()
        w.writerows(ROWS)
    print(f"wrote {len(ROWS)} rows -> {OUT}")

if __name__ == "__main__":
    main()
